### ISSUE TITLE
Azure Certifications

### ISSUE THREAD

**Issue by ShahidRasheed** [GulkyTechnologies/Learning#1]
1. [AZ-200 Microsoft Azure Developer Core Solutions](https://www.microsoft.com/en-us/learning/exam-az-200.aspx)
    - [ ] AZ-200T01: Select the appropriate Azure technology development solution
    - [ ] AZ-200T02: Develop for Azure storage
    - [ ] AZ-200T03: Develop Azure Platform as a Service solutions
    - [ ] AZ-200T04: Implement security in Azure development solutions
